### ISSUE TITLE
haxelib debugger or hxcpp-debugger ?

### ISSUE THREAD

**Issue by kiroukou** [HaxeFoundation/hxcpp-debugger#8]
Hi all.
Sorry but I didn't know where to ask this.

I found 2 different projects on haxelib, with different names, but described like doing the same thing (but not just a name thing since the version number is different).

Could someone give me some detail please?

Thanks

**Comment by Simn** [comment]
It's hxcpp-debugger, we renamed it because debugger was too generic.

I suppose we should remove the debugger one from haxelib to avoid confusion.

**Comment by kiroukou** [comment]
I would agree with that.

Also, it is a more general remark but testing the fact the hxcpp-debugger lib is embeded leads to an error (obviously)  "invalid operation"
```
#if hxcpp-debugger
...
#end
```
Maybe some name constraint on haxelib?

**Comment by Simn** [comment]
`#if hxcpp_debugger` should work.

**Comment by kiroukou** [comment]
Ok thank you Simon !

**Comment by Simn** [comment]
@back2dos: Are you still the haxelib-remove-guy nowadays? If so, please get rid of the "debugger" haxelib.

**Comment by back2dos** [comment]
@Simn done.

**Comment by Simn** [comment]
Thanks!
